### ISSUE TITLE
tensorflow/lite/experimental/micro/kernels/all_ops_resolver.h: No such file or directory

### ISSUE THREAD

**Issue by wallanoo** [arduino/ArduinoTensorFlowLiteTutorials#15]
When I upload the IMU_Classifier to the Arduino nano 33 sense BLE I obtain this error:

tensorflow/lite/experimental/micro/kernels/all_ops_resolver.h: No such file or directory

I have the Arduino_Tensorflowlite library 2.1.0-Alpha precompiled installed..

**Comment by wallanoo** [comment]
I found libraries in tensorflow/lite/micro

**Comment by myominhtet** [comment]
how get that. I tried but still got error

**Comment by jintolonappan** [comment]
@myominhtet 
You may need to change such lines to:

```
#include "tensorflow/lite/micro/all_ops_resolver.h"
#include "tensorflow/lite/micro/micro_error_reporter.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/schema/schema_generated.h"
#include "tensorflow/lite/version.h"
```

**Comment by pdp7** [comment]
I ran into this as well.

I had to remove 'experimental' from the paths:
```
#include <tensorflow/lite/micro/all_ops_resolver.h>
#include <tensorflow/lite/micro/micro_error_reporter.h>
#include <tensorflow/lite/micro/micro_interpreter.h>
```
