### ISSUE TITLE
error: 'AllOpsResolver' in namespace 'tflite::ops::micro' does not name a type  tflite::ops::micro::AllOpsResolver tflOpsResolver;

### ISSUE THREAD

**Issue by wallanoo** [arduino/ArduinoTensorFlowLiteTutorials#16]
When I upload the IMU_Classifier to the Arduino nano 33 sense BLE I obtain this error:

error: 'AllOpsResolver' in namespace 'tflite::ops::micro' does not name a type  tflite::ops::micro::AllOpsResolver tflOpsResolver;

I have the Arduino_Tensorflowlite library 2.1.0-Alpha precompiled installed..

**Comment by markpatterson27** [comment]
It looks like the namespace for AllOpsResolver has changed. (See: https://github.com/tensorflow/tensorflow/commit/e5dfc3bc38696060922b4d8a04d6e773467b9f08#diff-bef9994836e47ef462fa74510aa8ae34)

Try changing line 43 of IMU_Classifier to:
```c++
tflite::AllOpsResolver tflOpsResolver;
```
 (i.e. delete '`ops::micro::`')
