### ISSUE TITLE
COM stuck after uploading IMU Classifier sketch？

### ISSUE THREAD

**Issue by KXCY-AI** [arduino/ArduinoTensorFlowLiteTutorials#23]
New to Arduino, I follow with the Arduino TensorFlow Lite Tutorials and trained "GestureToEmoji" IMU Classifier model, which is deployed on BLE. It  worked well previously, yet its stuck a serial monitor these day, after upload sketch to the board. Where I can figure out more information about it?

**Comment by per1234** [comment]
I'm working on getting enough information to be able to investigate this issue in @KXCY-AI's Arduino Forum post about the same:
https://forum.arduino.cc/index.php?topic=709946

**Comment by KXCY-AI** [comment]
> I'm working on getting enough information to be able to investigate this issue in @KXCY-AI's Arduino Forum post about the same:
> https://forum.arduino.cc/index.php?topic=709946
> 
> Also posted at [arduino/ArduinoCore-nRF528x-mbedos#106](https://github.com/arduino/ArduinoCore-nRF528x-mbedos/issues/106)

Thanks per1234, the model runs well after downgrade to 1.1.6

**Comment by gtteixeira** [comment]
I am getting the same problem. Follow all the steps with success on training and test model using the colab. No problem. Download the model.h exactly as instructions. Compiled ok.

 But when you ask the serial monitor nothing happen. Completely freezing. I am trying to fix during 4 days with no success.


model file and compilation was ok:
![image](https://user-images.githubusercontent.com/28991408/100165994-6b00fc00-2e9a-11eb-8338-6c9b9d754e5a.png)

Freezing when call the serial monitor:
![image](https://user-images.githubusercontent.com/28991408/100166213-eb276180-2e9a-11eb-9a36-0f0f000a8c95.png)

I am using tensorflow 2.1.0
![image](https://user-images.githubusercontent.com/28991408/100166301-2aee4900-2e9b-11eb-8286-10382464a38b.png)

**Comment by Rainycat** [comment]
We've hit the exact same problem.  Adding some debugging with
Serial.println(), we can see that it never returns from the call to
"new tflite::MicroInterpreter()".

Arduino IDE version is 1.8.13

Arduino BLE 33 board support version is 1.1.6

Tensorflow library version is 2.1.0. ALPHA (IMU_Classifier failed to build against older versions)

Hope this helps someone narrow down the problem!

**Comment by BenLuchterhand** [comment]
> I'm working on getting enough information to be able to investigate this issue in @KXCY-AI's Arduino Forum post about the same:
> https://forum.arduino.cc/index.php?topic=709946
> 
> Also posted at [arduino/ArduinoCore-nRF528x-mbedos#106](https://github.com/arduino/ArduinoCore-nRF528x-mbedos/issues/106)

Hey, I'm new to Arduino so I apologize if this is a silly question, but how do I downgrade the core? I'm experience the same issue.

**Comment by Rainycat** [comment]
> We've hit the exact same problem. Adding some debugging with
> Serial.println(), we can see that it never returns from the call to
> "new tflite::MicroInterpreter()".

Just to update anyone else who is having this problem, after a lot of faff, we discovered that in MicroAllocator (called by MicroInterpreter instantiation), it checks the supplied arena is 16-byte aligned and errors out if it isn’t.  The fix is to declare the arena like this:

byte tensorArena[tensorArenaSize] __attribute__((aligned(16)));

(Although probably the real fix would be within the Arduino_TensorFlowLite
library to not do that check – does it make sense on these platforms?). 

Hope this helps :-3

**Comment by ugmurthy** [comment]
I have the same problem when i run the classifier on nano33 BLE sense.
The com port is frozen and I cannot upload any new sketch. I restarted nano and also rebooted my laptop. The existing classifier on the nano prevent any new sketches from being loaded onto the nano therefore cannot test the suggestion made by @Rainycat

**Comment by per1234** [comment]
Hi @ugmurthy. You can recover your board from the Mbed OS crash by:
1. Press and release the reset button on your board quickly twice. You should now see the "L" LED on the board pulsing, which means the bootloader is running. If you don't see the LED pulsing, you might not have gotten the timing of the button press right, so try again. The double reset causes the bootloader to run indefinitely (until the board is reset, powered off, or an upload is done).
1. Select the port of your board from the **Tools > Port** menu. The port number may be different when the bootloader is running so don't assume you already have the correct port selected.

Now you should be able to upload the sketch to your Arduino board.

**Comment by ugmurthy** [comment]
> > We've hit the exact same problem. Adding some debugging with
> > Serial.println(), we can see that it never returns from the call to
> > "new tflite::MicroInterpreter()".
> 
> Just to update anyone else who is having this problem, after a lot of faff, we discovered that in MicroAllocator (called by MicroInterpreter instantiation), it checks the supplied arena is 16-byte aligned and errors out if it isn’t. The fix is to declare the arena like this:
> 
> ```
> byte tensorArena[tensorArenaSize] __attribute__((aligned(16)));
> ```
> 
> (Although probably the real fix would be within the Arduino_TensorFlowLite
> library to not do that check – does it make sense on these platforms?).
> 
> Hope this helps :-3

Yes that helps - the classifier works! thank you

**Comment by ab-cp** [comment]
> Hi @ugmurthy. You can recover your board from the Mbed OS crash by:
> 
> 1. Press and release the reset button on your board quickly twice. You should now see the "L" LED on the board pulsing, which means the bootloader is running. If you don't see the LED pulsing, you might not have gotten the timing of the button press right, so try again. The double reset causes the bootloader to run indefinitely (until the board is reset, powered off, or an upload is done).
> 2. Select the port of your board from the **Tools > Port** menu. The port number may be different when the bootloader is running so don't assume you already have the correct port selected.
> 
> Now you should be able to upload the sketch to your Arduino board.

Both this and 16 bit alignment works!
