### ISSUE TITLE
Error when compiling in nRF52 Arduino interface

### ISSUE THREAD

**Issue by yang12313** [arduino/ArduinoTensorFlowLiteTutorials#4]
Hi,

Thank you for providing this great tutorial. I tried to implement this project on adafruit bluefruit nRF52 but get an error during the compilation. the link below is the model.h and .ino file I used and error details shown in readme file. 
https://github.com/yang12313/tensorflow_lite_nRF52.
Could you help me fix this issue. Thank you so much.

Best,

HY

**Comment by sandeepmistry** [comment]
Hi @yang12313,

Thank you for your interest in this tutorial. We've only tested it with the Arduino Nano 33 BLE Sense board. I would suggest you contact Adafruit support for further assistance on this topic.
