### ISSUE TITLE
Model Is Not Building 

### ISSUE THREAD

**Issue by darcstartech** [arduino/ArduinoTensorFlowLiteTutorials#7]
@lucach
@8bitkick 
@sandeepmistry 

Hi!  

I have created the attached .csv files (currently .txt so I can upload to GitHub) for the punch and flex gestures and cannot get them to create a model.  It seems to just generate nothing.  Not sure what I am doing wrong? 

[punch.txt](https://github.com/arduino/ArduinoTensorFlowLiteTutorials/files/3878271/punch.txt)
[flex.txt](https://github.com/arduino/ArduinoTensorFlowLiteTutorials/files/3878273/flex.txt)

<img width="1026" alt="Screen Shot 2019-11-21 at 11 46 41 PM" src="https://user-images.githubusercontent.com/49822264/69404024-60c18600-0cb9-11ea-89e7-562b3c3a2955.png">

**Comment by lucach** [comment]
Hi! I think it is probably due to the fact that you have "null"/"empty" values in your record set (double check what you are copy-pasting from the serial monitor, it shouldn't be the case).

```sh
> grep ,, flex.txt
,,,,,,
,,,,,,
,,,,,,
,,,,,,
,,,,,,
,,,,,,
,,,,,,
,,,,,,
,,,,,,
,,,,,,
```

**Comment by darcstartech** [comment]
Awesome, thank you!  That solved the issue.  

This is a great project, thank you for doing this and releasing it online. So cool!
