### ISSUE TITLE
Increasing accuracy 

### ISSUE THREAD

**Issue by darcstartech** [arduino/ArduinoTensorFlowLiteTutorials#8]
@lucach
@8bitkick
@sandeepmistry 

Thanks for doing this project, so cool!  

I have got my Arduino to become quite accurate at recognizing two gestures but it still messes up occasionally.  I have played around with training the model better, adjusting the G forces, and sample rate.  

What would you guys suggest to increase its accuracy in recognizing gestures?  Does it help to provide more example data when creating the model?  Are their other variables you would experiment with? 

Thanks!

**Comment by 8bitkick** [comment]
Hi @darcstartech we're glad the tutorial was a useful beginning for your tinyML journey :)  More example data will certainly help generalize the model - the tutorial is really just to get you acquainted with the end-to-end flow and with just a few samples it will not be the most accurate. Other areas to investigate are pre-filtering of the input data to remove noise and extract just the features you are interested in (FFT and low/high pass filtering) and well as different model architectures. To get deeper into the topic a good backgrounder is in the [OReilly TinyML book](https://www.oreilly.com/library/view/tinyml/9781492052036/) which was part of the inspiration behind this tutorial. I will close this issue as I don't think it it relates to a bug in the tutorial code, but if you have more questions feel free to post them on the Arduino Forum.
